application/recruitinfo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, ValidationError
from wtforms.validators import DataRequired, Optional, Length

from ..models import RecruitInfo


class EditRecruitInfo(FlaskForm):
    name = StringField('公司名', validators=[DataRequired()])
    position = StringField('需求职位', validators=[DataRequired()])
    email = StringField('邮箱', validators=[DataRequired()])
    tel = StringField('联系电话', validators=[DataRequired()])
    data = StringField('发布日期', validators=[DataRequired()])


class AddRecruitInfo(FlaskForm):
    name = StringField('公司名', validators=[DataRequired()])
    position = StringField('需求职位', validators=[DataRequired()])
    email = StringField('邮箱', validators=[DataRequired()])
    tel = StringField('联系电话', validators=[DataRequired()])
    data = StringField('发布日期', validators=[DataRequired()])

    def validate_name(form, field):
        recruitinfos = RecruitInfo.get_or_none(RecruitInfo.name == field.data)
        if recruitinfos is not None:
            raise ValidationError('用户名已经被使用')

application/recruitinfo/__init__.py
from flask import Blueprint

bp_recruitinfo = Blueprint('bp_recruitinfo', __name__)

from . import views

application/recruitinfo/views.py
from flask import render_template, flash, redirect, url_for
from playhouse.flask_utils import PaginatedQuery, get_object_or_404
from werkzeug.security import generate_password_hash
from flask_login import login_required


from ..models import RecruitInfo
from ..models import CVInfo


from .forms import AddRecruitInfo
from .forms import EditRecruitInfo
from . import bp_recruitinfo


@bp_recruitinfo.route('/list_recruitinfos')
@login_required
def list_recruitinfos():
    query = RecruitInfo.select().order_by(RecruitInfo.name)
    pg = PaginatedQuery(query, paginate_by=10, page_var='page', check_bounds=True)
    page = pg.get_page()
    page_count = pg.get_page_count()
    recruitinfos = pg.get_object_list()
    return render_template('recruitinfo/list_recruitinfos.html', recruitinfos=recruitinfos, page=page, page_count=page_count)


@bp_recruitinfo.route('/profile/<int:id>')
@login_required
def profile(id):
    recruitinfos = get_object_or_404(RecruitInfo, (RecruitInfo.id == id))
    return render_template('recruitinfo/profile.html', recruitinfos=recruitinfos)


@bp_recruitinfo.route('/delete_recruitinfos/<int:id>')
@login_required
def delete_recruitinfos(id):
    recruitinfos = RecruitInfo.select().where(RecruitInfo.id == id).get()
    recruitinfos.delete_instance()
    flash('删除成功')
    return redirect(url_for('bp_recruitinfo.list_recruitinfos'))


@bp_recruitinfo.route('/edit_recruitinfos/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_recruitinfos(id):
    recruitinfos = get_object_or_404(RecruitInfo, (RecruitInfo.id == id))
    form = EditRecruitInfo()
    if form.validate_on_submit():
        recruitinfos.name = form.name.data
        recruitinfos.position = form.position.data
        recruitinfos.email = form.email.data
        recruitinfos.tel = form.tel.data
        recruitinfos.data = form.data.data
        recruitinfos.save()
        flash('修改成功')
        return redirect(url_for('bp_recruitinfo.profile', id=recruitinfos.id))
    return render_template('recruitinfo/edit_recruitinfos.html', form=form, recruitinfos=recruitinfos)


@bp_recruitinfo.route('/add_recruitinfos', methods=['GET', 'POST'])
@login_required
def add_recruitinfos():
    form = AddRecruitInfo()
    if form.validate_on_submit():
        RecruitInfo.create(
            name=form.name.data,
            position=form.position.data,
            email=form.email.data,
            tel=form.tel.data,
            data=form.data.data
        )
        flash('添加成功')
        return redirect(url_for('bp_recruitinfo.list_recruitinfos'))
    return render_template('recruitinfo/add_recruitinfos.html', form=form)


@bp_recruitinfo.route('/list_recruitinfo/<string:name>')
@login_required
def list_recruitinfo1(name):
    query1 = RecruitInfo.select()
    query2 = get_object_or_404(CVInfo, (CVInfo.name == name))
    return render_template('recruitinfo/list_reandcv.html', query1=query1, query2=query2)

application/templates/recruitinfo/add_recruitinfos.html
{% extends 'welcome/page_news.html' %}
{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{{ url_for('bp_recruitinfo.add_recruitinfos') }}" method="post">
    <p>公司名称:<input name="name" type="text">
    {% if form.name.errors %}
         <span style="color:red;">
        {{ form.name.errors | join('<br>') }}
         </span>
        {% endif %}
    </p>
    <p>需求职位:<input name="position" type="text"></p>
    <p>类型:<input name="type" type="text"></p>
    <p>邮箱:<input name="email" type="text"></p>
    <p>联系电话:<input name="tel" type="text"></p>
    <p>日期：<input name="data" type="text">
{#        {% if form.password.errors %}#}
{#         <span style="color:red;">#}
{#        {{ form.password.errors | join('<br>') }}#}
{#         </span>#}
{#        {% endif %}#}
    </p>
{#	<p>性 别：<input type="radio" value="M" name="gender">男&nbsp;&nbsp;#}
{#	<input type="radio" name="gender" value="F">女</p>#}
{#	<p>角 色：<select size="1" name="role">#}
{#	<option value="teacher">教师</option>#}
{#	<option value="student">学生</option>#}
{#	<option selected>null</option>#}
{#	</select></p>#}
    <p><input type="submit"></p>
</form>
</body>
</html>
{% endblock %}

application/templates/recruitinfo/edit_recruitinfos.html
{% extends 'welcome/page_news.html' %}
{% block bio %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <form action="{{ url_for('bp_recruitinfo.edit_recruitinfos', id=recruitinfo.id) }}" method="post">
      <p>公司名：<input name="name" type="text" value="{{ recruitinfo.name }}"></p>
      <p>需求职位：<input name="position" type="text" value="{{ recruitinfo.position }}"></p>
      <p>类型：<input name="type" type="text" value="{{ recruitinfo.type }}"></p>
      <p>邮箱：<input name="email" type="text" value="{{ recruitinfo.email }}"></p>
      <p>联系电话：<input name="tel" type="text" value="{{ recruitinfo.tel }}"></p>
      <p>日期：<input name="data" type="text" value="{{ recruitinfo.data }}"></p>
{#      <p>性 别:#}
{#       <select name="gender" >#}
{#         <option value="M" {% if user.gender == 'M'%}selected{% endif %}>男</option>#}
{#         <option value="F" {% if user.gender == 'F' %}selected{% endif %}>女</option>#}
{#       </select>#}
{#      {% if form.gender.errors %}#}
{#       <span style="color:red;">#}
{#       {{ form.gender.errors | join('<br>') }}#}
{#       </span>#}
{#       {% endif %}#}
{#      </p>#}
      <p ><input type="submit"></p>
  </form>
</body>
</html>
{% endblock %}

application/templates/recruitinfo/list_reandcv.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
简历 <small>简历信息展示</small>
</h3>
{% endblock %}
{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>简历信息查询</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
{% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
          {% for message in messages  %}
            <li style="color: green">{{ message }}</li>
          {% endfor %}
      </ul>
     {% endif %}
{% endwith %}
  <table border="1" width="70%">
      <thead>
      <tr>
          <td>#</td>
          <td>ID</td>
          <td>求职者</td>
          <td>性别</td>
          <td>地址</td>
          <td>电话</td>
          <td>求职意向</td>
          <td>专业类型</td>
{#          <td>查看</td>#}
      </tr>
      </thead>
      <tbody name="t3">

      {% for query1 in query1 %}
      <tr>
      {% if query1.name == query2.name %}
          <td>{{ loop.index }}</td>
          <td>{{ query1.id }}</td>
          <td>{{ query2.name }}</td>
          <td>{{ query2.gender }}</td>
          <td>{{ query2.address }}</td>
          <td>{{ query1.tel }}</td>
          <td>{{ query1.position }}</td>
          <td>{{ query1.type }}</td>
{#          <td><a href="{{url_for('bp_corpinfo.profile2', id=query1.id)}}">查看</a></td>#}
      </tr>
          {% endif %}
      {% endfor %}
      </tbody>
  </table>
<button><a href="{{url_for('bp_cvinfo.list_cvinfos')}}">返回</a></button>
</body>
</html>
{% endblock %}

application/templates/recruitinfo/list_recruitinfos.html
{% extends 'welcome/page_news.html' %}
{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>公司信息查询</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
          {% for message in messages  %}
            <li style="color: green">{{ message }}</li>
          {% endfor %}
      </ul>
     {% endif %}
{% endwith %}
<p>
  <a href="{{ url_for('bp_recruitinfo.add_recruitinfos') }}">添加用户</a>
</p>
  <table border="1" width="70%">
      <thead>
      <tr>
          <td>#</td>
          <td>ID</td>
          <td>公司名</td>
          <td>需求职位</td>
          <td>类型</td>
          <td>邮箱</td>
          <td>联系电话</td>
          <td>日期</td>
          <td>详情</td>
          <td>操作1</td>
          <td>操作2</td>
      </tr>
      </thead>
      <tbody>
      {% for recruitinfo in recruitinfos %}
      <tr>
          <td>{{ loop.index }}</td>
          <td>{{ recruitinfo.id }}</td>
          <td>{{ recruitinfo.name }}</td>
          <td>{{ recruitinfo.position }}</td>
          <td>{{ recruitinfo.type }}</td>
          <td>{{ recruitinfo.email }}</td>
          <td>{{ recruitinfo.tel }}</td>
          <td>{{ recruitinfo.data }}</td>
          <td><a href="{{url_for('bp_recruitinfo.profile', id=recruitinfo.id)}}">查看</a></td>
          <td><a href="{{url_for('bp_recruitinfo.delete_recruitinfos', id=recruitinfo.id)}}">删除</a></td>
          <td><a href="{{url_for('bp_recruitinfo.edit_recruitinfos', id=recruitinfo.id) }}">修改</a></td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
{% if page > 1 %}
<a href="{{ url_for('list_recruitinfos', page=page-1) }}">上一页</a>
{% endif %}
<span>第{{ page }}页/共计{{ page_count }}页</span>
{% if page < page_count %}
<a href="{{ url_for('list_recruitinfos', page=page + 1) }}">下一页</a>
{% endif %}
</body>
</html>
{% endblock %}

application/templates/recruitinfo/profile.html
{% extends 'welcome/page_news.html' %}
{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li style="color: green">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

  <h1>{{ recruitinfos.name }}公司的信息</h1>
  <p>公司名：{{ recruitinfos.name }}</p>
  <p>需求职位：{{ recruitinfos.position }}</p>
  <p>类型：{{ recruitinfos.type }}</p>
  <p>邮箱：{{ recruitinfos.email }}</p>
  <p>联系方式：{{ recruitinfos.tel }}</p>
  <p>日期：{{ recruitinfos.data }}</p>
  <p><a href="{{ url_for('bp_recruitinfo.list_recruitinfos') }}">返回</a></p>
</body>
</html>
{% endblock %}