application/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, ValidationError
from wtforms.validators import DataRequired, Optional, Length
from ..models import User


class EditUser(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    nickname = StringField('姓名', validators=[DataRequired()])
    gender = SelectField('性别', validators=[DataRequired()], choices=(('M', '男'), ('F', '女')))
    # role = SelectField('角色', validators=[DataRequired()], choices=(('teacher', '教师'), ('student', '学生')))


class AddUser(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    password = StringField('密码', validators=[DataRequired(), Length(6, 20, '密码长度在6~20之间')])
    nickname = StringField('姓名', validators=[Optional()])
    gender = StringField('性别', validators=[DataRequired()])
    role = StringField('角色', validators=[DataRequired()])

    def validate_username(form, field):
        user = User.get_or_none(User.username == field.data)
        if user is not None:
            raise ValidationError('用户名已经被使用')

application/user/__init__.py
from flask import Blueprint

bp_user = Blueprint('bp_user', __name__)

from . import views

application/user/views.py
from flask import render_template, flash, redirect, url_for
from playhouse.flask_utils import PaginatedQuery, get_object_or_404
from werkzeug.security import generate_password_hash

from ..models import User

from .forms import AddUser
from .forms import EditUser
from . import bp_user


@bp_user.route('/list_users')
def list_users():
    query = User.select().order_by(User.username)
    pg = PaginatedQuery(query, paginate_by=10, page_var='page', check_bounds=True)
    page = pg.get_page()
    page_count = pg.get_page_count()
    users = pg.get_object_list()
    return render_template('user/list_users.html', users=users, page=page, page_count=page_count)


@bp_user.route('/profile/<int:id>')
def profile(id):
    user = get_object_or_404(User, (User.id == id))
    return render_template('user/profile.html', user=user)


@bp_user.route('/delete_user/<int:id>')
def delete_user(id):
    user = User.select().where(User.id == id).get()
    user.delete_instance()
    flash('删除成功')
    return redirect(url_for('bp_user.list_users'))


@bp_user.route('/edit_user/<int:id>', methods=['GET', 'POST'])
def edit_user(id):
    user = get_object_or_404(User, (User.id == id))
    form = EditUser()
    if form.validate_on_submit():
        user.username = form.username.data
        user.nickname = form.nickname.data
        user.gender = form.gender.data
        user.save()
        flash('修改成功')
        return redirect(url_for('bp_user.profile', id=user.id))
    return render_template('user/edit_user.html', form=form, user=user)


@bp_user.route('/add_user', methods=['GET', 'POST'])
def add_user():
    form = AddUser()
    if form.validate_on_submit():
        User.create(
            username=form.username.data,
            password=generate_password_hash(form.password.data),
            nickname=form.nickname.data,
            gender=form.gender.data,
            role=form.role.data
        )
        flash('添加成功')
        return redirect(url_for('bp_user.list_users'))
    return render_template('user/add_user.html', form=form)

application/templates/user/add_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{{ url_for('bp_user.add_user') }}" method="post">
    <p>用户名:<input name="username" type="text">
    {% if form.username.errors %}
         <span style="color:red;">
        {{ form.username.errors | join('<br>') }}
         </span>
        {% endif %}
    </p>
    <p>姓 名:<input name="nickname" type="text"></p>
    <p>密 码：<input type="password" name="password" size="20">
        {% if form.password.errors %}
         <span style="color:red;">
        {{ form.password.errors | join('<br>') }}
         </span>
        {% endif %}
    </p>
	<p>性 别：<input type="radio" value="M" name="gender">男&nbsp;&nbsp;
	<input type="radio" name="gender" value="F">女</p>
	<p>角 色：<select size="1" name="role">
	<option value="teacher">教师</option>
	<option value="student">学生</option>
	<option selected>null</option>
	</select></p>
    <p><input type="submit"></p>
</form>
</body>
</html>

application/templates/user/edit_user.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <form action="{{ url_for('bp_user.edit_user', id=user.id) }}" method="post">
      <p>用户名：<input name="username" type="text" value="{{ user.username }}"></p>
      <p>姓 名：<input name="nickname" type="text" value="{{ user.nickname }}"></p>
      <p>性 别:
       <select name="gender" >
         <option value="M" {% if user.gender == 'M'%}selected{% endif %}>男</option>
         <option value="F" {% if user.gender == 'F' %}selected{% endif %}>女</option>
       </select>
      {% if form.gender.errors %}#}
       <span style="color:red;">
       {{ form.gender.errors | join('<br>') }}
       </span>
       {% endif %}
      </p>
      <p ><input type="submit"></p>
  </form>
</body>
</html>

application/templates/user/list_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>信息查询</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
          {% for message in messages  %}
            <li style="color: green">{{ message }}</li>
          {% endfor %}
      </ul>
     {% endif %}
{% endwith %}
<p>
  <a href="{{ url_for('bp_user.add_user') }}">添加用户</a>
</p>
  <table border="1">
      <thead>
      <tr>
          <td>#</td>
          <td>ID</td>
          <td>用户名</td>
          <td>姓名</td>
          <td>密码</td>
          <td>性别</td>
          <td>角色</td>
          <td>详情</td>
          <td>操作1</td>
          <td>操作2</td>
      </tr>
      </thead>
      <tbody>
      {% for user in users %}
      <tr>
          <td>{{ loop.index }}</td>
          <td>{{ user.id }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.nickname }}</td>
          <td style="font-size:1px">{{ user.password }}</td>
          <td>{{ user.gender }}</td>
          <td>{{ user.role }}</td>
{#          <td>{{ user.birthdate }}</td>#}
          <td><a href="{{url_for('bp_user.profile', id=user.id)}}">查看</a></td>
          <td><a href="{{url_for('bp_user.delete_user', id=user.id)}}">删除</a></td>
          <td><a href="{{url_for('bp_user.edit_user', id=user.id) }}">修改</a></td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
{% if page > 1 %}
<a href="{{ url_for('list_users', page=page-1) }}">上一页</a>
{% endif %}
<span>第{{ page }}页/共计{{ page_count }}页</span>
{% if page < page_count %}
<a href="{{ url_for('list_users', page=page + 1) }}">下一页</a>
{% endif %}
</body>
</html>

application/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li style="color: green">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

  <h1>{{ user.nickname }}的个人信息</h1>
  <p>用户名：{{ user.username }}</p>
  <p>姓名：{{ user.nickname }}</p>
  <p>性别：{{ user.gender }}</p>
  <p>角色：{{ user.role }}</p>
  <p><a href="{{ url_for('bp_user.list_users') }}">返回</a></p>
</body>
</html>