application/corpsum/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, ValidationError
from wtforms.validators import DataRequired, Optional, Length

from ..models import CorpSum


class EditCorpSum(FlaskForm):
    name = StringField('公司名', validators=[DataRequired()])
    type = StringField('类别', validators=[DataRequired()])
    data = StringField('日期', validators=[DataRequired()])


class AddCorpSum(FlaskForm):
    name = StringField('公司名', validators=[DataRequired()])
    type = StringField('类别', validators=[DataRequired()])
    data = StringField('日期', validators=[DataRequired()])

    def validate_name(form, field):
        corpsums = CorpSum.get_or_none(CorpSum.name == field.data)
        if corpsums is not None:
            raise ValidationError('用户名已经被使用')

application/corpsum/__init__.py
from flask import Blueprint

bp_corpsum = Blueprint('bp_corpsum', __name__)

from . import views

application/corpsum/views.py
from flask import render_template, flash, redirect, url_for
from playhouse.flask_utils import PaginatedQuery, get_object_or_404
from flask_login import login_required
from werkzeug.security import generate_password_hash

from ..utilities import role_required
from ..models import CorpSum


from .forms import AddCorpSum
from .forms import EditCorpSum
from . import bp_corpsum


@bp_corpsum.route('/list_corpsums')
@login_required
def list_corpsums():
    query = CorpSum.select().order_by(CorpSum.id)
    pg = PaginatedQuery(query, paginate_by=10, page_var='page', check_bounds=True)
    page = pg.get_page()
    page_count = pg.get_page_count()
    corpsums = pg.get_object_list()
    return render_template('corpsum/list_corpsums.html', corpsums=corpsums, page=page, page_count=page_count)


@bp_corpsum.route('/profile/<int:id>')
@login_required
def profile(id):
    corpsums = get_object_or_404(CorpSum, (CorpSum.id == id))
    return render_template('corpsum/profile.html', corpsums=corpsums)


@bp_corpsum.route('/delete_corpsums/<int:id>')
@login_required
@role_required('er')
def delete_corpsums(id):
    corpsums = CorpSum.select().where(CorpSum.id == id).get()
    corpsums.delete_instance()
    flash('删除成功')
    return redirect(url_for('bp_corpsum.list_corpsums'))


@bp_corpsum.route('/edit_corpsums/<int:id>', methods=['GET', 'POST'])
@login_required
@role_required('er')
def edit_corpsums(id):
    corpsums = get_object_or_404(CorpSum, (CorpSum.id == id))
    form = EditCorpSum()
    if form.validate_on_submit():
        corpsums.name = form.name.data
        corpsums.type = form.type.data
        corpsums.data = form.data.data
        corpsums.save()
        flash('修改成功')
        return redirect(url_for('bp_corpsum.profile', id=corpsums.id))
    return render_template('corpsum/edit_corpsums.html', form=form, corpsums=corpsums)


@bp_corpsum.route('/add_corpsums', methods=['GET', 'POST'])
@login_required
@role_required('er')
def add_corpsums():
    form = AddCorpSum()
    if form.validate_on_submit():
        CorpSum.create(
            name=form.name.data,
            type=form.type.data,
            idata=form.data.data
        )
        flash('添加成功')
        return redirect(url_for('bp_corpsum.list_corpsums'))
    return render_template('corpsum/add_corpsums.html', form=form)

application/templates/corpsum/add_corpsums.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
公司 <small>公司信息展示</small>
</h3>
{% endblock %}

{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
<form action="{{ url_for('bp_corpsum.add_corpsums') }}" method="post">
    <p>公司名称:<input name="name" type="text">
    {% if form.name.errors %}
         <span style="color:red;">
        {{ form.name.errors | join('<br>') }}
         </span>
        {% endif %}
    </p>
    <p>类 型:<input name="type" type="text"></p>
    <p>日 期：<input name="data" type="date">
{#        {% if form.password.errors %}#}
{#         <span style="color:red;">#}
{#        {{ form.password.errors | join('<br>') }}#}
{#         </span>#}
{#        {% endif %}#}
    </p>
    <img border="0" src="{{ url_for('static', filename='BG/dandelion.png')}}" width="535" height="331" align="right">
{#	<p>性 别：<input type="radio" value="M" name="gender">男&nbsp;&nbsp;#}
{#	<input type="radio" name="gender" value="F">女</p>#}
{#	<p>角 色：<select size="1" name="role">#}
{#	<option value="teacher">教师</option>#}
{#	<option value="student">学生</option>#}
{#	<option selected>null</option>#}
{#	</select></p>#}
    <p><input type="submit"></p>
</form>
</body>
</html>
{% endblock %}

application/templates/corpsum/edit_corpsums.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
公司 <small>公司信息展示</small>
</h3>
{% endblock %}

{% block bio %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
  <form action="{{ url_for('bp_corpsum.edit_corpsums', id=corpsums.id) }}" method="post">
      <p>公司名：<input name="name" type="text" value="{{ corpsums.name }}"></p>
      <p>类  型：<input name="type" type="text" value="{{ corpsums.type }}"></p>
      <p>日  期：<input name="data" type="data" value="{{ corpsums.data }}"></p>

{#      <p>性 别:#}
{#       <select name="gender" >#}
{#         <option value="M" {% if user.gender == 'M'%}selected{% endif %}>男</option>#}
{#         <option value="F" {% if user.gender == 'F' %}selected{% endif %}>女</option>#}
{#       </select>#}
{#      {% if form.gender.errors %}#}
{#       <span style="color:red;">#}
{#       {{ form.gender.errors | join('<br>') }}#}
{#       </span>#}
{#       {% endif %}#}
{#      </p>#}
      <p ><input type="submit"></p>
  </form>
</body>
</html>
{% endblock %}

application/templates/corpsum/list_corpsums.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
公司 <small>公司信息展示</small>
</h3>
{% endblock %}

{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>公司信息查询</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
{% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
          {% for message in messages  %}
            <li style="color: green">{{ message }}</li>
          {% endfor %}
      </ul>
     {% endif %}
{% endwith %}
<p>
  <a href="{{ url_for('bp_corpsum.add_corpsums') }}">添加用户</a>
</p>
  <table border="1" width="70%">
      <thead>
      <tr>
          <td>#</td>
          <td>ID</td>
          <td>公司名</td>
          <td>类型</td>
          <td>日期</td>
          <td>公司详情</td>
          <td>职位详情</td>
          <td>操作1</td>
          <td>操作2</td>
      </tr>
      </thead>
      <tbody>
      {% for corpsum in corpsums %}
      <tr>
          <td>{{ loop.index }}</td>
          <td>{{ corpsum.id }}</td>
          <td>{{ corpsum.name }}</td>
          <td>{{ corpsum.type }}</td>
          <td>{{ corpsum.data }}</td>
          <td><a href="{{url_for('bp_corpsum.profile', id=corpsum.id)}}">查看公司信息</a></td>
          <td><a href="{{url_for('bp_corpinfo.list_corpinfo1', name=corpsum.name)}}">查看职位需求</a></td>
          <td><a href="{{url_for('bp_corpsum.delete_corpsums', id=corpsum.id)}}">删除</a></td>
          <td><a href="{{url_for('bp_corpsum.edit_corpsums', id=corpsum.id) }}">修改</a></td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
{% if page > 1 %}
<a href="{{ url_for('list_corpsums', page=page-1) }}">上一页</a>
{% endif %}
<span>第{{ page }}页/共计{{ page_count }}页</span>
{% if page < page_count %}
<a href="{{ url_for('list_corpsums', page=page + 1) }}">下一页</a>
{% endif %}
</body>
</html>
{% endblock %}

application/templates/corpsum/profile.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
公司 <small>公司信息展示</small>
</h3>
{% endblock %}

{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li style="color: green">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

  <h1>{{ corpsums.name }}公司的信息</h1>
  <p>公司名：{{ corpsums.name }}</p>
  <p>类型：{{ corpsums.type }}</p>
  <p>日期：{{ corpsums.data }}</p>
  <p><a href="{{ url_for('bp_corpsum.list_corpsums') }}">返回</a></p>
</body>
</html>
{% endblock %}