application/corpinfo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, ValidationError
from wtforms.validators import DataRequired, Optional, Length

from ..models import CorpInfo


class EditCorpInfo(FlaskForm):
    name = StringField('公司名', validators=[DataRequired()])
    biography = StringField('公司简介', validators=[DataRequired()])
    address = StringField('公司地址', validators=[DataRequired()])
    email = StringField('公司邮箱', validators=[DataRequired()])
    tel = StringField('联系电话', validators=[DataRequired()])


class AddCorpInfo(FlaskForm):
    name = StringField('公司名', validators=[DataRequired()])
    biography = StringField('公司简介', validators=[DataRequired()])
    address = StringField('公司地址', validators=[DataRequired()])
    email = StringField('公司邮箱', validators=[DataRequired()])
    tel = StringField('联系电话', validators=[DataRequired()])

    def validate_name(form, field):
        corpinfos = CorpInfo.get_or_none(CorpInfo.name == field.data)
        if corpinfos is not None:
            raise ValidationError('用户名已经被使用')

application/corpinfo/__init__.py
from flask import Blueprint

bp_corpinfo = Blueprint('bp_corpinfo', __name__)

from . import views

application/corpinfo/views.py
from flask import render_template, flash, redirect, url_for
from playhouse.flask_utils import PaginatedQuery, get_object_or_404
from flask_login import login_required
from werkzeug.security import generate_password_hash


from ..models import CorpInfo
from ..models import User


from .forms import AddCorpInfo
from .forms import EditCorpInfo
from . import bp_corpinfo


@bp_corpinfo.route('/list_corpinfos')
@login_required
def list_corpinfos():
    query = CorpInfo.select().order_by(CorpInfo.name)
    pg = PaginatedQuery(query, paginate_by=10, page_var='page', check_bounds=True)
    page = pg.get_page()
    page_count = pg.get_page_count()
    corpinfos = pg.get_object_list()
    return render_template('corpinfo/list_corpinfos.html', corpinfos=corpinfos, page=page, page_count=page_count)


@bp_corpinfo.route('/profile/<int:id>')
@login_required
def profile(id):
    corpinfos = get_object_or_404(CorpInfo, (CorpInfo.id == id))
    return render_template('corpinfo/profile.html', corpinfos=corpinfos)


@bp_corpinfo.route('/delete_corpinfos/<int:id>')
@login_required
def delete_corpinfos(id):
    corpinfos = CorpInfo.select().where(CorpInfo.id == id).get()
    corpinfos.delete_instance()
    flash('删除成功')
    return redirect(url_for('bp_corpinfo.list_corpinfos'))


@bp_corpinfo.route('/edit_corpinfos/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_corpinfos(id):
    corpinfos = get_object_or_404(CorpInfo, (CorpInfo.id == id))
    form = EditCorpInfo()
    if form.validate_on_submit():
        corpinfos.name = form.name.data
        corpinfos.biography = form.biography.data
        corpinfos.address = form.address.data
        corpinfos.email = form.email.data
        corpinfos.tel = form.tel.data
        corpinfos.save()
        flash('修改成功')
        return redirect(url_for('bp_corpinfo.profile', id=corpinfos.id))
    return render_template('corpinfo/edit_corpinfos.html', form=form, corpinfos=corpinfos)


@bp_corpinfo.route('/add_corpinfos', methods=['GET', 'POST'])
@login_required
def add_corpinfos():
    form = AddCorpInfo()
    if form.validate_on_submit():
        CorpInfo.create(
            name=form.name.data,
            biography=form.biography.data,
            address=form.address.data,
            email=form.email.data,
            tel=form.tel.data
        )
        flash('添加成功')
        return redirect(url_for('bp_corpinfo.list_corpinfos'))
    return render_template('corpinfo/add_corpinfos.html', form=form)


@bp_corpinfo.route('/list_corpinfo/<string:name>')
@login_required
def list_corpinfo1(name):
    query1 = User.select()
    query2 = get_object_or_404(CorpInfo, (CorpInfo.name == name))
    return render_template('corpinfo/list_corpall.html', query1=query1, query2=query2)


# @bp_corpinfo.route('/profile2/<int:id>')
# @login_required
# def profile2(id):
#     corpinfos = get_object_or_404(query1 ,query1.id == id)
#     return render_template('corpinfo/profile.html', corpinfos=corpinfos)

application/templates/corpinfo/add_corpinfos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{{ url_for('bp_corpinfo.add_corpinfos') }}" method="post">
    <p>公司名:<input name="name" type="text">
    {% if form.name.errors %}
         <span style="color:red;">
        {{ form.name.errors | join('<br>') }}
         </span>
        {% endif %}
    </p>
    <p>公司简介:<input name="biography" type="text"></p>
    <p>公司地址：<input name="address" type="text">
{#        {% if form.password.errors %}#}
{#         <span style="color:red;">#}
{#        {{ form.password.errors | join('<br>') }}#}
{#         </span>#}
{#        {% endif %}#}
    </p>
	<p>公司邮箱：<input name="\email" type="text"></p>&nbsp;
{#	<input type="radio" name="gender" value="F">女</p>#}
	<p>联系电话：<input name="tel" type="text"></p>
{#	<option value="teacher">教师</option>#}
{#	<option value="student">学生</option>#}
{#	<option selected>null</option>#}
{#	</select></p>#}
    <p><input type="submit" value="提交"></p>
</form>
</body>
</html>

application/templates/corpinfo/corp_profile.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
公司 <small>公司信息展示</small>
</h3>
{% endblock %}

{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li style="color: green">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

  <h1>{{ query2.name }}的具体公司的信息</h1>
   <p>面试官姓名：{{ query1.nickname }}</p>
   <p>联系方式：{{ query2.tel }}</p>
   <p>公司地址：{{ query2.address }}</p>
   <p>公司简介：{{ query1.biography }}</p>
   <p></p>
   <p></p>
  <p><a href="{{ url_for('bp_corpinfo.list_corpinfo1') }}">返回</a></p>
</body>
</html>
{% endblock %}

application/templates/corpinfo/edit_corpinfos.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <form action="{{ url_for('bp_corpinfo.edit_corpinfos', id=corpinfos.id) }}" method="post">
      <p>公司名名：<input name="name" type="text" value="{{ corpinfos.name }}"></p>
      <p>公司简介：<input name="biography" type="text" value="{{ corpinfos.biography }}"></p>
      <p>公司地址：<input name="address" type="text" value="{{ corpinfos.address }}"></p>
      <p>公司邮箱：<input name="email" type="text" value="{{ corpinfos.email }}"></p>
      <p>联系电话：<input name="tel" type="text" value="{{ corpinfos.tel }}"></p>
{#      <p>性 别:#}
{#       <select name="gender" >#}
{#         <option value="M" {% if corpinfo.gender == 'M'%}selected{% endif %}>男</option>#}
{#         <option value="F" {% if corpinfo.gender == 'F' %}selected{% endif %}>女</option>#}
{#       </select>#}
{#      {% if form.gender.errors %}#}
{#       <span style="color:red;">#}
{#       {{ form.gender.errors | join('<br>') }}#}
{#       </span>#}
{#       {% endif %}#}
{#      </p>#}
      <p ><input type="submit"></p>
  </form>
</body>
</html>

application/templates/corpinfo/list_corpall.html
{% extends 'welcome/page_news.html' %}
{% block headr %}
<h3 class="page-title">
公司 <small>公司信息展示</small>
</h3>
{% endblock %}

{% block bio %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>公司信息查询</title>
</head>
<body background="{{ url_for('static', filename='BG/scrapes.jpg')}}">
{% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
          {% for message in messages  %}
            <li style="color: green">{{ message }}</li>
          {% endfor %}
      </ul>
     {% endif %}
{% endwith %}
  <table border="1" width="70%">
      <thead>
      <tr>
          <td>#</td>
          <td>ID</td>
          <td>公司名</td>
          <td>地址</td>
          <td>面试官姓名</td>
          <td>性别</td>
          <td>公司电话</td>
          <td>公司简介</td>
{#          <td>查看</td>#}
      </tr>
      </thead>
      <tbody name="t3">

      {% for query1 in query1 %}
      <tr>
          {% if query1.role =='er'  %}
          <td>{{ loop.index }}</td>
          <td>{{ query1.id }}</td>
          <td>{{ query2.name }}</td>
          <td>{{ query2.address }}</td>
          <td>{{ query1.nickname }}</td>
          <td>{{ query1.gender }}</td>
          <td>{{ query2.tel }}</td>
          <td>{{ query1.biography }}</td>
{#          <td><a href="{{url_for('bp_corpinfo.profile2', id=query1.id)}}">查看</a></td>#}
      </tr>
          {% endif %}
      {% endfor %}
      </tbody>
  </table>
<button><a href="{{url_for('bp_corpsum.list_corpsums')}}">返回</a></button>
</body>
</html>
{% endblock %}

application/templates/corpinfo/list_corpinfos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>信息查询</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
          {% for message in messages  %}
            <li style="color: green">{{ message }}</li>
          {% endfor %}
      </ul>
     {% endif %}
{% endwith %}
<p>
  <a href="{{ url_for('bp_corpinfo.add_corpinfos') }}">添加用户</a>
</p>
  <table border="1" width="70%">
      <thead>
      <tr>
          <td>#</td>
          <td>ID</td>
          <td>公司名</td>
          <td>公司简介</td>
          <td>公司地址</td>
          <td>公司邮箱</td>
          <td>联系方式</td>
          <td>详情</td>
          <td>操作1</td>
          <td>操作2</td>
      </tr>
      </thead>
      <tbody>
      {% for corpinfo in corpinfos %}
      <tr>
          <td>{{ loop.index }}</td>
          <td>{{ corpinfo.id }}</td>
          <td>{{ corpinfo.name }}</td>
          <td>{{ corpinfo.biography }}</td>
          <td>{{ corpinfo.address }}</td>
          <td>{{ corpinfo.email }}</td>
          <td>{{ corpinfo.tel }}</td>
          <td><a href="{{url_for('bp_corpinfo.profile', id=corpinfo.id)}}">查看</a></td>
          <td><a href="{{url_for('bp_corpinfo.delete_corpinfos', id=corpinfo.id)}}">删除</a></td>
          <td><a href="{{url_for('bp_corpinfo.edit_corpinfos', id=corpinfo.id) }}">修改</a></td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
{% if page > 1 %}
<a href="{{ url_for('list_corpinfos', page=page-1) }}">上一页</a>
{% endif %}
<span>第{{ page }}页/共计{{ page_count }}页</span>
{% if page < page_count %}
<a href="{{ url_for('list_corpinfos', page=page + 1) }}">下一页</a>
{% endif %}
</body>
</html>

application/templates/corpinfo/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li style="color: green">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

  <h1>{{ corpinfos.name }}的个人信息</h1>
  <p>公司名：{{ corpinfos.name }}</p>
  <p>公司简介：{{ corpinfos.biography }}</p>
  <p>公司地址：{{ corpinfos.address }}</p>
  <p>公司邮箱：{{ corpinfos.email }}</p>
  <p>联系方式：{{ corpinfos.tel }}</p>
  <p><a href="{{ url_for('bp_corpinfo.list_corpinfos') }}">返回</a></p>
</body>
</html>